### ISSUE TITLE
Author name won´t show if you disable author bio in swift theme

### ISSUE THREAD

**Issue by gabu69** [ahmedkaludi/accelerated-mobile-pages#3131] opened 2019-05-02 19:35 UTC
Also if you **enable Author Name** and **disable Author Bio** 

Author name won´t show at top.  

It should appear on top and dissapear only the author bio box at the end of the article, but both dissapear.

**Comment by Zabi09** [comment] 2019-05-06 06:35
If someone wants only author name - https://prnt.sc/nkxdc0 without the author bio then?

**Comment by MohammedKaludi** [comment] 2019-05-11 10:04
:+1: ready to merge.

**Comment by MohammedKaludi** [comment] 2019-05-15 08:59
Pushed in 0.9.97.52

**Comment by gabu69** [comment] 2019-05-21 06:16
Im sorry but this bug is still there, now even author names wont appear 
Example: https://www.okchicas.com/entretenimiento/tv/game-of-thrones-final-dividio-todos/amp/

Also if i disable Author Bio, author name or photo wont even appear

**Comment by jsm386** [comment] 2019-05-21 15:23
Using 0.9.97.53 can confirm this bug as well (author Bio disabled, author name will not appear). Example at https://vinepair.com/booze-news/study-cork-screwcap-wine-consumer-value/?amp

**Comment by MARQAS** [comment] 2019-05-24 05:46
@jsm386, are you using AMP Layouts? The issue is due to AMP Layouts and it has been resolved in 1.5.3, please update it.

**Closed by MARQAS** 2019-05-24 05:46 UTC
Labels: [Priority: HIGH], bug

**Comment by gabu69** [comment] 2019-05-24 06:07
Hi @MARQAS, I just updated,  Theres still a bug

if I enable Author name and disable autho bio 

Author name wont show at top still

**Comment by MARQAS** [comment] 2019-05-24 06:13
Can you please contact us at team@magazine3.com? We will look into this issue of yours and will resolve it immediately
