### ISSUE TITLE
Need Meta Description on amp pages

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#741] opened 2017-03-27 10:18 UTC
Need to create Meta Description on amp pages.

Ref:  https://secure.helpscout.net/conversation/339284283/11691/?folderId=1060551

**Comment by spanishcostas** [comment] 2017-03-27 13:15
New here so not sure if I should be uploading the evidence of my problem but I will do that anyway just in case. I use the Yoast SEO plugin but the Meta Description tag is not being created and populated with the corresponding description for AMP pages.. I have attached both the Amp and non Amp source code with the website link below (although AMP is disabled on my main page)
![amp](https://cloud.githubusercontent.com/assets/26714557/24358066/268a7790-1300-11e7-9d00-c2da4f4e01df.jpg)
![no-amp](https://cloud.githubusercontent.com/assets/26714557/24358065/268210b4-1300-11e7-9bad-09fffe959aac.jpg)


https://costasonline.com/

**Comment by khaledMohammed000** [comment] 2017-04-06 18:16
In progress ... needs testing and still, code lies only in my dev environment...will push asap

**Comment by MohammedKaludi** [comment] 2017-04-08 07:17
why i'm seeing blank meta desc on home page and in post page 
home page: http://take.ms/0ffBv
post page:  http://take.ms/ijzD2

**Comment by spanishcostas** [comment] 2017-04-08 13:31
Not sure if you are asking me that @MohammedKaludi but I use Yoast for Meta Descriptions, I fill out each Meta Description manually on each page, My site is actually in English and Spanish, The English uses pages and the Spanish uses posts but the problem is the same on both. Not sure if that helps you or not... Plugin seems to be working quite well to be honest, good work from you guys :+1:

**Comment by MohammedKaludi** [comment] 2017-04-08 16:13
@spanishcostas I was referring to KhaledMohammed the dev who is working on this fix. Thank you for your feedback and I'm sure this issue will be fixed after this update.

Thank you very much once again for your feedback and I'm glad that you liked this plugin.

Mohammed Kaludi.

**Comment by MohammedKaludi** [comment] 2017-04-08 16:14
Working in the test and ready to push live.

**Closed by MohammedKaludi** 2017-04-08 16:13 UTC

**Comment by spanishcostas** [comment] 2017-04-08 16:16
Fix the Meta Description issue @MohammedKaludi and I gladly give you a well deserved 5 star rating on the Wordpress plugin repository :+1:
