### ISSUE TITLE
Problem with Displaying Tables with design 2

### ISSUE THREAD

**Issue by zabi332** [ahmedkaludi/accelerated-mobile-pages#1376] opened 2017-11-07 11:05 UTC
Only 2 out of 3 table columns are shown in design 2 but tried with Design 1 and Design 3 the table is working fine,  

Ref: https://secure.helpscout.net/conversation/460983361/17922?folderId=1060551

**Comment by MARQAS** [comment] 2017-11-15 04:56
Update from user: The issue is resolved in the last update.

**Comment by MohammedKaludi** [comment] 2017-11-16 07:43
Reply from the User 

> Hello Marqas, 
The issue is resolved!. After the latest update the plugin is working absolutely fine.
Thank you so much for resolving the issue on a priority.
Best Regards,
Chaitanya

**Closed** 2017-11-16 07:42 UTC
