### ISSUE TITLE
 Error_log implode() php

### ISSUE THREAD

**Issue by CG-TEAM** [ahmedkaludi/accelerated-mobile-pages#3307] opened 2019-06-10 06:14 UTC
Hi,

First thank you for this amazing plugin with many features. I purchase pro version.

I’m using enfold theme. When i update my amp plugin from 0.9.97.51.1 to recent version i have an error_log in my server:

implode(): Invalid arguments passed in /.../wp-content/themes/enfold/config-templatebuilder/avia-template-builder/php/shortcode-helper.class.php on line 163

When i downgrade my plugin to 0.9.97.51.1 the error gone. My Enfold theme version is: 4.5.7

Please help me for this issues.

Thank you,

**Comment by ahmedkaludi** [comment] 2019-06-10 08:43
Please send the website details via https://ampforwp.com/support/

so we can debug into the code

**Comment by CG-TEAM** [comment] 2019-06-10 09:31
> 
> 
> Please send the website details via https://ampforwp.com/support/
> 
> so we can debug into the code

I send it before about 4 week's ago for 2 times. but no one answer me.

**Comment by ahmedkaludi** [comment] 2019-06-10 15:19
That's strange, can you share the email address that you used to send the email?

**Comment by CG-TEAM** [comment] 2019-06-11 05:41
> 
> 
> That's strange, can you share the email address that you used to send the email?

regedit2007@yahoo.com

**Comment by ahmedkaludi** [comment] 2019-06-17 08:03
we were having some issues with our email, we will directly contact you via operations@magazine3.com

**Comment by CG-TEAM** [comment] 2019-06-18 06:10
> 
> 
> we were having some issues with our email, we will directly contact you via [operations@magazine3.com](mailto:operations@magazine3.com)

Hi,

I'm reply my website account detail via email

**Comment by CG-TEAM** [comment] 2019-06-22 09:57
Hi,
12 days ago i create this topic and 4 days ago i email my website account detail but no one answer and solved my issues

**Comment by ahmedkaludi** [comment] 2019-06-25 08:43
I'm sorry, let me have a look at it. There was a problem with our email server with Yahoo emails, so we had to communicate through an email which is out of the system, I'll check the email and get back to you asap

**Comment by MARQAS** [comment] 2019-06-25 11:22
The error is coming after resolving #3124 
`ampforwp_enfold_theme_compatibility` is the root cause of it.
We are removing shortcodes in some way and enfold theme is trying to use its own shortcodes in some other way. So we have to find a better way to resolve this issue to avoid errors

**Comment by ahmedkaludi** [comment] 2019-06-26 07:11
@CG-TEAM  We have verified this bug and we will fix this in upcoming updates.

**Comment by ahmedkaludi** [comment] 2019-06-26 16:38
@CG-TEAM 
I apologise for asking for the details, please revoke the access as we have understood the WordPress plugin guidelines. 

@MARQAS we have to respect the guidelines and not ask for any details.

I'm locking this thread for further discussion.

**Comment by MARQAS** [comment] 2019-06-26 17:14
@ahmedkaludi I didn't asked for it. I recreated and resolved it on my Local server.

**Comment by MohammedKaludi** [comment] 2019-06-28 10:42
Ready to merge.

**Comment by MohammedKaludi** [comment] 2019-07-02 17:19
Pushed in 0.9.97.61

**Closed by MohammedKaludi** 2019-07-02 17:19 UTC
Labels: NEED FAST REVIEW, [Priority: HIGH], bug
