### ISSUE TITLE
meta information changed

### ISSUE THREAD

**Issue by dgmdonna** [ahmedkaludi/accelerated-mobile-pages#4938] opened 2021-02-24 18:59 UTC
Good afternoon, I have a problem, I use All in One SEO plugin, the titles, keyword and meta are all set correctly, in the desktop version look perfect.
But when I use amp, the keywords and meta of the home page disappears and the title is "Blog". AIOSEO is configured in AMP. It happens to me on more than one site.
I need to solve it ASAP

**Comment by Zabi09** [comment] 2021-02-25 09:38
@dgmdonna Will you please send me your website URL for me to check and also are you using the latest version of AMPforWP and All in one SEO plugin and have you selected the All in one SEO in SEO section of our plugin - https://prnt.sc/106eemn

Please let me know

**Comment by dgmdonna** [comment] 2021-02-25 11:57
In both sites the plugins are updated, in both they are set as shown in the image (the Canonical option is activated, I don't know if that changes anything).

https://rccd.looktotheright.com/
In RCCD I introduced through functions the title, description and keywords, but it duplicates the title.

https://www.looktotheright.com/
In LTTR it is not bringing me the metadata and therefore the function does not work.

The function is as follows:

function add_aiosp_title_to_amp_pages( $amp_template ) {?>
	<title><?php echo esc_html( get_post_meta(get_the_ID(), '_aioseop_title', true ) );?></title>    
<?php }
add_action( 'amp_post_template_head', 'add_aiosp_title_to_amp_pages' );


Greetings

**Comment by Zabi09** [comment] 2021-02-26 07:25
@dgmdonna Will you please give us the export of your ALL in one SEO settings and also the settings of the AMP options panel, So that we can import it and fix it

**Comment by dgmdonna** [comment] 2021-02-26 13:47
Please find attached the requested files

[RCCD-settings.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/6049958/RCCD-settings.zip)
[LTTR-Settings.zip](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/6049986/LTTR-Settings.zip)

**Comment by Zabi09** [comment] 2021-03-03 05:34
@dgmdonna I have tested a lot and found that the issue is coming due to All in one SEO plugin, will you please contact them once and I am sure there will help you in fixing this issue, 

Please inform them once and do let us know if your issue got fixed or not

**Comment by Zabi09** [comment] 2021-03-05 12:48
@dgmdonna any update?

**Comment by Zabi09** [comment] 2021-03-12 12:36
https://wordpress.org/support/topic/meta-of-the-amp-home-page-disappears/

**Comment by Zabi09** [comment] 2021-03-17 10:38
Message from ALL in One SEO Developer - I will be looking into the issue later this week. If we need to make changes on our end, then they might be included in the next update in early April, otherwise, it might be early May.

So closing the ticket

**Closed by Zabi09** 2021-03-17 10:38 UTC
Labels: Need More Data
