### ISSUE TITLE
Rare Case scenario with IMG insertion

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2892] opened 2019-02-13 11:37 UTC
when we can't figure out dimensions for an image then it applying the unknown height and width.

Ref:  https://secure.helpscout.net/conversation/755621603/50725?folderId=1914712

screenshot: http://take.ms/XPSJb
http://take.ms/WdDZt

**Comment by MARQAS** [comment] 2019-02-26 07:42
I have resolved the issue on users end (by clearing the transient). And now the issue is only in ATF and that too due to his own styling which he is adding in ATF.

**Comment by MARQAS** [comment] 2019-04-02 05:36
It has been resolved here: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2931
Closing this ticket.

**Closed by MARQAS** 2019-04-02 05:36 UTC
Labels: bug
