### ISSUE TITLE
The button CSS not appearing in the AMP added with the Gutenberg button module

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4572] opened 2020-06-22 12:55 UTC
Ref: https://secure.helpscout.net/conversation/1194433726/135953?folderId=3611365

If the user is adding the CSS like the gradient, background color from the Gutenberg button module then the CSS is not loading in AMP. 

Screenshots:
https://prnt.sc/t4bego
on local in non AMP: https://prnt.sc/t4ay2m
In AMP: https://prnt.sc/t4axu0

At the user's end: 
 https://prnt.sc/t4awhn

Steps to create the issue on local:
1. Add the button through the Gutenberg module module
2. Now, goto the button block and add some gradient color and save the changes

URL: https://technicaljayendra.com/brave-browser-review/amp/

**Comment by MohammedKaludi** [comment] 2020-06-24 05:29
sanitize the color while merging. 
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cf9dbdef800a6738b33dc43407bc9d685256b158#diff-6aa5512f7dd8d5ce60fc97b0f340912cR6878

**Comment by MohammedKaludi** [comment] 2020-06-25 00:02
Pushed in 1.0.54

**Comment by jayendrasinhrajput** [comment] 2020-06-25 09:14
The issue is not fixed @ahmedkaludi ,
Look at amp page - https://technicaljayendra.com/advanced-system-optimizer-review/amp/
Look at this nonamp page - https://technicaljayendra.com/advanced-system-optimizer-review/

Observe buttons it does not appear on the page (when you hover on that button then and then it will appear)

**Comment by jayendrasinhrajput** [comment] 2020-06-25 09:17
@ahmedkaludi You need to release a new update and make sure to  this library - wp-includes/css/dist/block-library ( used by Gutenberg)

I think ampforwp plugin blocks this library so buttons do not look as they want to look.
Exclude this block library from adsforwp

**Comment by MohammedKaludi** [comment] 2020-06-25 09:20
Because the gradient button take large amount of css and we cannot include every single css due to the max limit of css that can be used, the gradient buttons will only work when css optimization is enabled under performance section.
 
Can you enable and test it and do let us know is it working as expected?

**Comment by jayendrasinhrajput** [comment] 2020-06-25 10:29
I enabled it but it does not work as expected

this is what happened when I enabled this option.

Look at this before hover - https://prnt.sc/t66v0j
after hover - https://prnt.sc/t66vqx

the button does not show at all.

**Comment by jayendrasinhrajput** [comment] 2020-06-26 13:35
Still, it does not fix after latest update - 6/26/202 6:45 @MohammedKaludi

**Comment by MohammedKaludi** [comment] 2020-06-29 05:39
@jayendrasinhrajput can you please let us know what theme you are using? 

and Do you use any other Gutenberg plugins?

**Comment by jayendrasinhrajput** [comment] 2020-06-29 07:03
No I am using default editor !

**Comment by MohammedKaludi** [comment] 2020-06-29 11:09
> No I am using default editor @MohammedKaludi and also i tried everything that i can by removing gradient from button but still it does not works on amp pages.


Can you please let me know your theme, because we have tested it with twenty nineteen, twenty twenty theme and its working fine in our tests, also can you please let me know what performance plugins you are using?

**Comment by jayendrasinhrajput** [comment] 2020-06-29 11:25
Blocksy theme and lightspeed plugin that comes with lightspeed server @MohammedKaludi

**Comment by Zabi09** [comment] 2020-06-29 13:05
Hi @jayendrasinhrajput,

I tried to recreate your issue on my end by adding a button in Gutenberg but the issue is not recreating on my end,
Here are the screenshots:
Added Button module - https://prnt.sc/t8h8r0
Enabled Optimize CSS - https://prnt.sc/t8h8xv
Output - https://prnt.sc/t8h977

Will you please let us know exactly how you are adding and also can you please give us the entire post modules so that we can import on our end and check it once,

And also I found that all your buttons are the same blue color and can you try to add the below css in global section of the AMP panel and check the result once and also please clear the cache after making changes.

Here is the CSS - 
```
:root .has-midnight-gradient-background {
    background: linear-gradient(135deg, rgb(2, 3, 129), rgb(40, 116, 252));
    border-radius: 0;
}
```

Please try this and let us know and we are happy to help you.

**Comment by jayendrasinhrajput** [comment] 2020-06-29 13:55
@Zabi09 at my end button does not appear it will only show plain blue text when i hover on it

**Comment by Zabi09** [comment] 2020-06-30 10:10
Okay, Can you tell me exactly how you are adding the button, and have you tried the CSS which I have given above?

**Comment by jayendrasinhrajput** [comment] 2020-06-30 12:02
@Zabi09 thanks it works ! @MohammedKaludi  i add css provided by @Zabi09  into custom css option and my problem was solved but it only works for gradient type button it does not work for default button.  I am using blocksy theme please try to create same situation from your end @MohammedKaludi  and then test it if possible

**Comment by MohammedKaludi** [comment] 2020-07-01 12:25
Ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4523

The user change his site to AMP, only the button text appears. He is using Gutenberg to add buttons.

Reference: https://wordpress.org/support/topic/button-issue-6/

**Comment by Zabi09** [comment] 2020-08-24 10:30
I have checked your website and found that the button with gradient color and also the normal color are appearing fine on your website now, So closing this ticket

**Closed by Zabi09** 2020-08-24 10:30 UTC
Labels: [Priority: HIGH], bug
