### ISSUE TITLE
PWA Module has Ruined all AMP Pages + Schema & Structured Data plugin

### ISSUE THREAD

**Issue by ArtFl-2** [ahmedkaludi/accelerated-mobile-pages#3190] opened 2019-05-15 21:13 UTC
Today I have switched on the PWA support in the AMPforWP settings and have activated the PWA module. 
At first, it looked fine but soon all my AMP posts and pages became invalid and I  received warnings from Google Search Console.
![New AMP errors](https://user-images.githubusercontent.com/49853569/57808959-dbd33e00-7764-11e9-92f0-04ee10f17892.jpg)

![AMP new errors](https://user-images.githubusercontent.com/49853569/57809019-e988c380-7764-11e9-9460-f39cc7385e78.jpg)

I switched off the PWA support and deleted the PWA module from the installed plugins.\

AMP pages and posts became valid again but some other strange errors remained highlighted at the top of my posts and pages:
![New errors](https://user-images.githubusercontent.com/49853569/57809380-9ebb7b80-7765-11e9-8271-156adc4ebbbb.jpg)

Because of these errors, I had to deactivate the Schema & Structured Data for WP plugin as well.
After I deactivated it, all the error warnings have disappeared.

Now I don't know what to do because:
1/ I want to use the Schema & Structured Data for WP plugin but if I activate it, the errors return back.
2/ I would like to use PWA but the PWA module kills AMP pages.

**Comment by ahmedkaludi** [comment] 2019-05-15 21:33
I'm Sorry for the inconvenience.

The problem is that we are not able to recreate this issue, only you can help us fix this one.


Can you please help me fix this issue? 

Can you please contact me via ampforwp.com/support ?

I'll personally help you fix this issue

**Comment by ArtFl-2** [comment] 2019-05-15 21:36
Ok, thank you. Tomorrow.

**Comment by MARQAS** [comment] 2019-05-16 11:30
@ArtFl-2, That will be fine. And I am pretty sure you'll get the solution there. 
I am closing this ticket, for now, We will open it once will know the core reason for this issue and obviously if it is related to this plugin. 
Thank you :)

**Closed by MARQAS** 2019-05-16 11:30 UTC
Labels: Need Testing, [Priority: HIGH]
