### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Laxmikanth2502** [ahmedkaludi/accelerated-mobile-pages#4148] opened 2020-02-06 12:51 UTC
Ref:https://secure.helpscout.net/conversation/1059361502/107167?folderId=3528427

User getting high memory usage issue after installing the amp

**Comment by mohammadsharfuddin** [comment] 2020-03-02 04:46
@Zabi09 @Laxmikanth2502 It has been more than 40 days (25 days + 15 days Email conversation). NO resolution yet. Check out the screenshot. High Memory crossing 1 GB, first I was on 1GB only after facing this problem I moved to Cloud and still facing the same problem. @Laxmikanth2502 you know it better I have explained you step by step in an Email thread.
![Screenshot_2](https://user-images.githubusercontent.com/20258057/75646171-2aa18400-5c62-11ea-82fc-c69d3c605db6.jpg)

**Comment by Zabi09** [comment] 2020-03-02 11:09
@mohammadsharfuddin We have debugged your issue a lot but we are unable to find any errors till now and for testing purpose will you please deactivate "Top 10 plugin" for 24 hours and we will check the result and let you know

**Comment by mohammadsharfuddin** [comment] 2020-03-02 11:45
@Zabi09 Done. Deactivated Top 10 Plugin and will monitor from my side too for 24 hours. Thanks

**Comment by Zabi09** [comment] 2020-03-03 09:26
@mohammadsharfuddin Thank you for deactivating the Top 10 plugin but still the memory is showing around 900-950 MB that means the issue is not related to that plugin. Will you please tell us exactly what amount of memory was used to be before activating our plugin? and also will you deactivate our AMP plugin and check whether your memory is back to the normal amount.

**Comment by mohammadsharfuddin** [comment] 2020-03-04 12:57
@Zabi09 Yes, memory is still showing around 950 - 1064. Before activating the AMP plugin memory was at 50 - 120 on its ideal time. Upon traffic Real Time 15-20 the usage of memory was 250-280 maximum 300. But after installing the AMP it directly jumped to 1024. I was not able to login my dashboard also for 2-3 days. Then I upgrade to Cloud Hosting with 3GB Ram. And now memory is constantly touching 1024.

![Screenshot_1](https://user-images.githubusercontent.com/20258057/75881566-c258cb00-5e38-11ea-9304-a5b42bd51ad4.jpg)

**Comment by MohammedKaludi** [comment] 2020-03-04 14:02
@Zabi09 please do let me know when you start working on this ticket in the morning, we will together look into it .

**Comment by Zabi09** [comment] 2020-03-05 10:30
@mohammadsharfuddin I have deactivated our AMPforWP plugin and also AdsforWP plugin and now we will monitor your memory for 48 hours and will see what will be the result of it

**Comment by mohammadsharfuddin** [comment] 2020-03-05 12:15
@Zabi09 okay. Thanks will monitor too.

**Comment by mohammadsharfuddin** [comment] 2020-03-07 05:54
@Zabi09 Please check now memory has reduced at least from 1064 to 829 upon deactivating AMPforWP plugin. However it is still high. But, I am unable to find the exact solution for this. Does AMPforWP Plugin takes this much memory 200+ ?
![Screenshot_3](https://user-images.githubusercontent.com/20258057/76137732-936d6f80-6059-11ea-9a4c-d09b68cc4d6f.jpg)

**Comment by MohammedKaludi** [comment] 2020-03-07 08:27
@mohammadsharfuddin Yes, the plugin will take some memory to perform as it. As the nature of the AMP it does not run in background , it runs everytime because it has to generate the AMP pages everytime.

But we are working on the optimisations, it should reduce some resources but it as I mentioned it is needs some memory to perform.

If you see any room for improvements or do you see any slow query then do let us know, we are here to help you.

**Comment by mohammadsharfuddin** [comment] 2020-03-07 08:28
@MohammedKaludi Thank You so much for the help.

**Comment by MohammedKaludi** [comment] 2020-03-07 17:38
I'm closing this ticket for now, once we find any concrete evidence we will reopen the ticket.

**Closed by MohammedKaludi** 2020-03-07 17:38 UTC
Labels: [Priority: HIGH], bug
