### ISSUE TITLE
Content alignment 

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#2507] opened 2018-09-07 01:07 UTC
Hello, it seems that the alignment doesn’t work, while in editor text and media alignment shows fine, but when previewed or published the amp won’t work.

**Comment by Zabi09** [comment] 2018-09-07 13:08
@SageFargo Will you please elaborate more about your issue and please provide us some screenshots of your issue so that first we will understand the issue and try to find the solution

**Comment by Zabi09** [comment] 2018-09-27 06:59
@SageFargo if you align the text and images in WordPress editor then it works perfectly in AMP as well as the non-AMP version like - 
http://take.ms/muK49
http://take.ms/6ryTS
http://take.ms/yKlTH

Will you please provide us the exact URL of that page and tell us exactly where you have aligned the text and images So that I will check once and let you know.

**Comment by SageFargo** [comment] 2018-10-06 19:39
@Zabi09 I align the text and images in every post/page and in Wordpress editor it works just fine. But, when you view the post or page it is not aligned. This issue is site-wide, meaning every page and every post won't work.

see examples below:
**Pages:**
https://fargo1ife.com/contact-us/
https://fargo1ife.com/terms-of-use/

**Posts:**
https://fargo1ife.com/five-of-our-most-favourite-sneakers-and-where-to-get-them/
https://fargo1ife.com/our-favorite-pieces-off-alpha-industries-fw-18-collection-drop/
https://fargo1ife.com/our-favorite-pieces-off-pinkdolphins-fall-18-collection/

**Comment by Zabi09** [comment] 2018-10-18 13:38
The issue is fixed on the user's end

**Closed by Zabi09** 2018-10-18 13:38 UTC
Labels: bug
