### ISSUE TITLE
Disallowed attribute or attribute value present in HTML tag.. Please fix it ASAP

### ISSUE THREAD

**Issue by 7bhabesh** [ahmedkaludi/accelerated-mobile-pages#4803] opened 2020-10-30 17:09 UTC
Example URLs where the issue is present [https://www.dealntech.com/privacy-policy/amp/](url) [https://www.dealntech.com/xiaomi-mi-redmi-android-11-update-phones/amp/](url)

Recently I think the same issue is reported by JoeStambray here.

**Comment by MohammedKaludi** [comment] 2020-10-30 19:47
This is happening due to the latest version of yoast and the issue will be fixed in the new version of yoast 
Check this ticket: https://github.com/Yoast/wordpress-seo/issues/16255#issuecomment-717884124

In the meantime to fix the issue is to disable the ‘Enhanced Slack sharing’ feature in SEO>General>Features.

**Comment by JoeStambray** [comment] 2020-10-30 23:02
Thanks. I had a feeling that the problem was Yoast. It just came so close to an AMP update that I didn't know.

**Comment by MohammedKaludi** [comment] 2020-11-04 09:30
Issue resolved after the update of Yoast.
Closing the ticket.

**Closed by MohammedKaludi** 2020-11-04 09:30 UTC
