### ISSUE TITLE
Image size smaller than recommended size warning [No Aqua resizer]

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#2878] opened 2019-02-08 13:27 UTC
Image size smaller than recommended size warning [No Aqua resizer]
Ref: https://secure.helpscout.net/conversation/771341180/54402?folderId=2322652

**Comment by Rkroy** [comment] 2019-02-08 13:28
Another User: https://secure.helpscout.net/conversation/767559868/53532?folderId=2322652

**Comment by jwbats** [comment] 2019-02-08 14:31
Relevant:

https://wordpress.org/support/topic/automatic-creation-of-1280px-wide-featured-images-bugs/

**Comment by MARQAS** [comment] 2019-02-11 11:46
We have already resolved this issue. One is having an issue due to our Structured Data plugin. And other is using some other schema.

**Comment by ahmedkaludi** [comment] 2019-02-13 06:53
Closing because this is caused by other theme/plugin compatibility.

**Closed by ahmedkaludi** 2019-02-13 06:53 UTC

**Comment by jwbats** [comment] 2019-02-13 13:02
What theme/plugin caused the problem?

I've currently manually replaced my featured images with 1200px wide images...

Will future versions of this plugin simply use that, instead of try to create their own 1280px wide image? And will it correctly display the dimensions of my own 1200px image, rather than the plugin's 1280px image?
