### ISSUE TITLE
No 404 error for invalid URLs

### ISSUE THREAD

**Issue by AlexeyKosov** [ahmedkaludi/accelerated-mobile-pages#2042] opened 2018-04-19 10:47 UTC
I noticed that invalid URLs containing /amp/ won't show the 404 error.
It's not a big deal, but it would be great to properly handle invalid URLs for SEO purposes.
Example: https://www.cadcrowd.com/blog/amp/asdasdasdasdasdasd/ shows the same page as https://www.cadcrowd.com/blog/amp/ though it should show the 404 page.

**Comment by Frenchomatic** [comment] 2018-04-26 10:39
So far the 404 problem persists in AMP takeover on design 2 - I uploaded the 404.php file to design 2, updated features.php and updated components/theme-loader.php . No joy. The 404 template doesn't show and it still redirects to the nearest valid root path.

**Comment by Sejiro-Hiko** [comment] 2018-04-26 12:03
@Frenchomatic can I check it on your given site to me in our previous conversation?

**Comment by Frenchomatic** [comment] 2018-04-26 12:06
Sure. Remember this is a production site so you need to let me know what you have done or what needs to be done.  It is not in AMP takeover.  I tested the modifications on another site in AMP takeover but please go ahead and get it working on a hybrid system first. 



On 26 Apr 2018, at 14:03, Sejiro-Hiko <notifications@github.com> wrote:

@Frenchomatic <https://github.com/Frenchomatic> can I check it on your given site to me in our previous conversation?

**Comment by Frenchomatic** [comment] 2018-04-26 12:16
I just made sure it was all as normal 9.8.5.5 and I get this and when ever amp is in the path, it goes to the nearest part of the root which is valid. 


For example https://www.ecole-ski-evasion.fr/amp/rubbish goes to https://www.ecole-ski-evasion.fr/amp/

Normal 404 still works of course. 


When I tried on a system in AMP takeover with your mods it doesn't work at all. Let me know if and when you want to work on that as the issue is different. I solve it on AMP takeover by making a modification to redirect.php but it is a hack in the top of the file and probably only works in my situation. What my hack does is send any non-existent page to my old non canonical styled 404. 





Here is an example, 

https://www.ubac-ski.com/rubbish - > give canconcial 404 . I can't seem to get you AMP styled 404.php to fire with your mods. . 


David



On 26 Apr 2018, at 14:06, TemplateCodes <admin@templatecodes.com> wrote:

Sure. Remember this is a production site so you need to let me know what you have done or what needs to be done.  It is not in AMP takeover.  I tested the modifications on another site in AMP takeover but please go ahead and get it working on a hybrid system first. 



On 26 Apr 2018, at 14:03, Sejiro-Hiko <notifications@github.com <mailto:notifications@github.com>> wrote:

@Frenchomatic <https://github.com/Frenchomatic> can I check it on your given site to me in our previous conversation?

**Comment by Sejiro-Hiko** [comment] 2018-04-27 07:06
@Frenchomatic can you please also add the latest commit also on your end and check, thanks!

**Comment by Frenchomatic** [comment] 2018-04-27 08:28
1. This is not working in AMP takeover. 
2. This works in normal hybrid system canconical + amp

Comments - the idea is for it to work in AMP takeover. On a hybrid system you probably wouldn't need that template and would probably want the canconical type of 404 to appear - hope that make sense.

**Comment by Frenchomatic** [comment] 2018-04-27 11:14
Doesn't seem to be working in AMP takeover - let me check I have go it all

replace features.php , replace theme-loader.php , create 404.pgp and put it into design2 folder. Nothing else and not other changes.

**Comment by Frenchomatic** [comment] 2018-04-27 11:33
I can get a 404 page to display in AMP takeoverdoing this right at the top of redirect.php but as above it needs to be an AMP styled one really. 

```
function ampforwp_check_amp_page_status() {
  global $redux_builder_amp, $wp;
  $hide_cats_amp = '';
  $hide_cats_amp = is_category_amp_disabled();
  if ( ampforwp_is_amp_endpoint() ) {if(is_404()){ global $wp_query;
  $wp_query->set_404();
  status_header( 404 );
  nocache_headers();
        include( get_query_template( '404' ) );
        die();
 }

    if ( (is_archive()
```

**Comment by MohammedKaludi** [comment] 2018-06-21 15:04
Closing the ticket as the base issue is solved, and regarding domain.com/amp/rubbish as AMP pages are created based on the regular HTML pages, so if regular HTML page is non-existent then creating an AMP page for that will not make sense. But might be useful if the full website is AMP-based. 

This can be improved in future.

**Closed by MohammedKaludi** 2018-06-21 15:04 UTC
