### ISSUE TITLE
Only the front page is available as AMP

### ISSUE THREAD

**Issue by CryssDOTnet** [ahmedkaludi/Accelerated-Mobile-Pages#78] opened 2016-09-18 19:57 UTC
Hi!

Thanks for this great plugin, but I have one issue: Only the main page has a AMP version. If I click on other pages or posts I get the normal website. In the options panel I can disable AMP on specific sites but none a selected. Could this be a bug?

When I first installed the plugin and tried the AMP version I _think_ AMP worked also for the other pages and posts. Not 100% sure.

Thanks,
Chris

tierfoto.cm.de

The website has a page as entry page/main page. If I visit http://tierfoto-cm.de?amp the blog view is the main page.

**Comment by MohammedKaludi** [comment] 2016-09-18 20:08
Hi Chris,
Thank you for using this plugin.

Are you sure you checked it on other pages, as I can see it is working on single pages http://take.ms/eeX4w3

Regarding the options panel issue, I will check it once again and will let you know.

**Comment by CryssDOTnet** [comment] 2016-09-18 20:26
What exactly did you do?

If I type in http://tierfotocm.de?amp the address line changes to http://tierfoto-cm.de/?amp and I get the blog view. If I click "navigate" all the links have no ?amp in it and therefore lead me to the normal view.

Furthermore, I don't have the social icons on the bottom although they are activated in the option panel.

**Comment by nicholasgriffintn** [comment] 2016-09-18 22:01
Yeah, it no longer adds ?amp to the links automatically, link the plugin used to, that's the issue that @CryssDOTnet is mentioning I think, which I have also noticed.

**Comment by CryssDOTnet** [comment] 2016-09-18 22:04
ATM I messed up my site by trying to figure out why my theme returns a blank page only on SSL. So you can't access my site for testing.

**Comment by nicholasgriffintn** [comment] 2016-09-18 22:40
@CryssDOTnet I was just looking at your site, it's rather strange.

You should update your PHP, it's version PHP/5.4.45, and maybe make sure that everything else is updated alongside it, then you might find the issue is resolved.

**Comment by CryssDOTnet** [comment] 2016-09-18 22:44
I am playing around atm with different PHP versions and settings as I have a problem with my themes. I get a blank page only when accessing over SSL.

Is PHP 7.0 ok? Or better 5.6?

**Comment by nicholasgriffintn** [comment] 2016-09-18 22:47
@CryssDOTnet I have never had a problem with PHP 7.0 on any of my own sites since I started using it, however, it could cause some issues with compatibility.

That said, given the speed increase that PHP 7.0 provides, as well as better overall coding, you should definitely enable PHP 7.0.1 if you can and then Iron out any issues that you might find after by switching things out. Mostly poorly coded things won't work with PHP 7.0, so it's better to just get rid of anything that doesn't work with it anyway.

**Comment by CryssDOTnet** [comment] 2016-09-18 22:49
OK. Thanks!

**Comment by nicholasgriffintn** [comment] 2016-09-18 22:51
@CryssDOTnet sorry, I think you missed my edit, here it is again just to help:

> Also a suggestion: have you tried swapping themes to Twenty Twelve? Will that load on HTTPS? Just for testing purposes. If it does, then you need to edit your original themes code until that works with HTTPS.

**Comment by CryssDOTnet** [comment] 2016-09-18 23:04
Yes. Twenty Twelve works, I tried that already. Thanks. I don't have any "coding skills". I see what I can do about it.

I wonder what http and https could make any difference theme-wise....

**Comment by CryssDOTnet** [comment] 2016-09-19 09:04
I tried the AMP pluggin with a wordpress default theme Twenty Fifteen and it doesn't generate any AMP links

**Comment by nicholasgriffintn** [comment] 2016-09-19 09:08
@CryssDOTnet It is generating links, as you can see here (https://tierfoto-cm.de/2016/09/17/drei-turmfalken-auf-einen-streich/?amp), but what it isn't doing is making links within amp pages an amp link, I have that same problem atm.

BTW: great news that HTTPS works on Twenty Twelve, that means that there's something wrong with the other theme that you were using, if you can't edit the code, I would suggest looking for another theme if possible.

**Comment by CryssDOTnet** [comment] 2016-09-19 13:38
Are we the only ones having this issue?

**Comment by ahmedkaludi** [comment] 2016-09-26 14:26
Hey @CryssDOTnet  

I have just checked the website URL and it seems to be working fine. Can you please confirm the issue?

**Comment by ahmedkaludi** [comment] 2016-09-27 05:32
I'm a little confused at this moment. Could you please rephrase the exact issue you are having rightnow?

**Comment by nicholasgriffintn** [comment] 2016-09-27 08:26
@ahmedkaludi Hey, I'm getting the same issue, so I'll explain it for you.

Basically, you can go to the URL fine, it will work. However, if you click on a link, say one of the posts on the AMP homepage, it will load the original URL for that article, not the AMP URL for that article.

**Comment by CryssDOTnet** [comment] 2016-09-27 11:51
nicholasgriffintn is right. Same here.

**Comment by CryssDOTnet** [comment] 2016-10-04 22:07
Any news on this?

**Comment by ahmedkaludi** [comment] 2016-10-16 19:43
Hey @CryssDOTnet 

Really sorry for the delay in getting back to you. Can you update to the latest version, then flush the rewrite and then check if it works fine?

**Comment by CryssDOTnet** [comment] 2016-10-17 07:00
I have updated to 8.5.3 flushed all caches and still the same problem.

**Comment by Lesrad** [comment] 2016-10-17 10:30
I think what they are saying is:

When in amp (mode) all links should remain in amp (mode) not go to regular blog mode, (there is already a view in normal blog mode option) it will improve user experience as well as improve actual functionality if users could continue browsing the entire site in amp mode and not just the page they landed on.

**Comment by CryssDOTnet** [comment] 2016-10-17 10:39
Yes. Absolutely correct @Lesrad 
I thought that is the user experience one would expect. Other opinions?

**Comment by khaledMohammed000** [comment] 2016-11-29 19:37
This is resolved in 0.8.8 update

**Closed by khaledMohammed000** 2016-11-29 19:37 UTC
Labels: NEXT UPDATE
