### ISSUE TITLE
Rare issue with Thrive Architect

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/accelerated-mobile-pages#2954] opened 2019-03-12 06:17 UTC
When WP Bakery and Thrive Architect plugin is Activated the output is not properly rendering.
check this screenshot: http://take.ms/rIdyf

The issue is not recreated on local server

Ref:  https://secure.helpscout.net/conversation/796849155/58558?folderId=1914712

**Comment by MARQAS** [comment] 2019-03-13 07:22
The issue is resolved on user's end and we don't exactly know where and what's the cause. 
Just check if it is recreated or not, if not we can close this ticket

**Comment by pegazee** [comment] 2019-03-13 12:35
I've tried to recreate the issue on my local server but unable to recreate the issue. We can close this ticket.

**Closed by pegazee** 2019-03-13 12:35 UTC
Labels: Need Testing
