### ISSUE TITLE
Page Builder Latest Posts Category Module 

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3927] opened 2019-12-09 16:28 UTC
When using **Page Builder** category module, all categories show featured images in the same dimensions, but when choosing the **Latest Posts** category, featured images show in different dimensions. Also, in single post, the related and recent posts are showing fine with the same dimensions, which means the problem is in the **Page Builder** code. 

![screen4444](https://user-images.githubusercontent.com/40724154/70453553-a2bc3b80-1ab1-11ea-9680-dd9e4cefd931.png)

**Comment by MohammedKaludi** [comment] 2019-12-26 11:34
Ready to merge.

**Comment by SageFargo** [comment] 2019-12-26 16:20
Hi, 

You’ve meant? Merge what?

**Comment by MohammedKaludi** [comment] 2019-12-27 10:37
@SageFargo that is for our internal communication.

We use a workflow to manage and fix the issue and that is part of it.

That means the issue is fixed in development area and it is ready to deploy, and will be pushed in future updates.

**Comment by SageFargo** [comment] 2019-12-28 12:59
Thank you, looking forward for this fix.

**Comment by MohammedKaludi** [comment] 2019-12-31 20:24
Pushed in 1.0.6

**Closed by MohammedKaludi** 2019-12-31 20:24 UTC
Labels: NEXT UPDATE, [Priority: HIGH], bug
