### ISSUE TITLE
AMP not working

### ISSUE THREAD

**Issue by richardmillstein** [ahmedkaludi/accelerated-mobile-pages#4292] opened 2020-03-18 10:57 UTC
I have the same issue with presidentialinaugurationparade.com as I did with chelseaschimney.com which you already fixed.

**Comment by richardmillstein** [comment] 2020-03-18 11:15
<img width="907" alt="Screen Shot 2020-03-18 at 7 15 17 AM" src="https://user-images.githubusercontent.com/34913206/76955273-40f94200-68e8-11ea-8c9c-c04a397bd117.png">

**Comment by MohammedKaludi** [comment] 2020-03-18 13:10
Hi @richardmillstein 

Thank you for creating the ticket.

The issue is coming due to a setting in SG optimizer plugin, which is not compatible with AMP.

But good news is we have fixed this in this ticket: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/4287 and made it compatible with SG optimizer plugin.

The issue is under testing rightnow and once the testing is done we will release it in the public.

In the meantime you con turnoff this option (https://monosnap.com/file/dkxY6QfaCBKSuMccrl0BYbkuu71Obq) from the SG optimizer and your site should be AMP validated. 


I'm closing this ticket for now as the issue has been fixed in #4287 .

**Closed by MohammedKaludi** 2020-03-18 13:10 UTC
