### ISSUE TITLE
6 AMP Error Issues in Google Search Console

### ISSUE THREAD

**Issue by Empathyfine** [ahmedkaludi/accelerated-mobile-pages#4894] opened 2021-01-07 13:59 UTC
Please how do I resolve the following 6 AMP Error issues as seen in my Google webmaster?

Error 1: Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head.

Error 2: Custom JavaScript is not allowed.

Error 3: Tag or text which is only allowed inside the body section found outside of the body section.

Error 4: Craw Issue

Error 5. URL Not Found(404)
N|B: Meanwhile there is no 404 URL

Error 6. Referenced AMP URL is Not an AMP

Example of page with the error;
https://www.visaflux.com/opera-mini-apk-download-opera-mini-browser-app-download-opera-mini-download/amp/

I am using "AMP for WP" - Accelerated Mobile Pages for WordPress By Ahmed Kaludi, Mohammed Kaludi

Please I need help @Zabi09 and @MohammedKaludi

**Comment by Empathyfine** [comment] 2021-01-07 14:16
Meanwhile, I have exported the AMP JSON file, and here is the link, please check and help me resolve this. See the JSON File Export of my AMP. Looking forward!

https://www.dropbox.com/s/sshsp5jypja7cgo/Visaflux%20AMP%20Export%20File%20for%20JSON.json?dl=0

**Comment by Zabi09** [comment] 2021-01-08 10:20
@Empathyfine I have checked your website and found that you are adding Adsense Ads in the wrong way - https://prnt.sc/wiwqn3 - This code was supposed to be inside the body tag but you have added it in the header and due to that you are having these errors.

And I have imported the AMP JSON file which you have sent me but did not find any amp-ad tag in our AMP settings. Will you tell me how you are adding Adsense Ads in AMP?

**Comment by Empathyfine** [comment] 2021-01-08 13:01
@Zabi09 I have removed the Ad code from the header now. And I have made sure I added the right code in the right places in the AMP for WP plugin.

Meanwhile, I used "quick Adsense" plugin to input the AMP Ad codes in the body, Just the way I did in my second website.

But it seems the issue is NOT yet resolved. Meanwhile, the whole settings now is exactly the way I did them in my second website which has no Issues at the moment.

But now that I have made changes, I exported the current JSON files for AMP for WP settings again. Please kindly help me check again if everything is fine now. See below the link to the new JSON file. Please note that I added the Adsense code to the right places in the AMP plugin.


https://www.dropbox.com/s/93od8ul7d4tfgc4/Visaflux%20AMP%20for%20WP%20JSON%20file%202.json?dl=0

**Comment by Empathyfine** [comment] 2021-01-08 13:02
@Zabi09  I also found this other Error:

"An AMP component 'script' tag is present, but unused."

Please help me out.

**Comment by Empathyfine** [comment] 2021-01-09 15:54
@Zabi09  Please can someone help me out on this, attached is a screenshot of the error in Search Console. I inserted Ads the right way, yet I still encounter the AMP issues. Please help!

![AMP issue Capture](https://user-images.githubusercontent.com/76563864/104096168-2939e280-529b-11eb-9d0a-3b782eb0f83b.PNG)

**Comment by Empathyfine** [comment] 2021-01-11 10:39
@Zabi09  please can I get some helpful recommendation.

**Comment by Zabi09** [comment] 2021-01-12 06:45
@Empathyfine I have tested your website now and found that it is valid - https://search.google.com/test/amp?id=h18xBx7-kdCfdQagMVsSxw and I have also found that the ads code are properly placed now.

And if you face any issue/errors/problem with the advertisement in AMP then I highly recommend you to use Ads by WP QUADS - https://wordpress.org/plugins/quick-adsense-reloaded/ which is fully compatible with our AMP plugin and its free and if you use any plugin like quick AdSense plugin etc then we need to check and verify if the things are working as expected or not BUT if you use WP QUADS then we will sure you that the ads will work 100% for sure.

Hope it helps

**Comment by Empathyfine** [comment] 2021-01-13 18:40
@Zabi09 thank you for your response....

But I am still having some issues, the following three Errors still persist;

1. Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head.

2. Custom JavaScript is not allowed.

3. Tag or text which is only allowed inside the body section found outside of the body section.

Example of my URLs with issue is https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/

But I want to follow your recommendation by switching to Ads by WP QUADS plugin for my AMP ads inside content body instead of the current Quick Adsense Plugin I am using to display Ads in the content body.

Let me see if that will help. I will update here.

Attached below is the image PREVIEW of the Error; (Not everything was captured though)

![image](https://user-images.githubusercontent.com/76563864/104494665-067b3700-55d7-11eb-8651-1928aa69cac5.png)

**Comment by Empathyfine** [comment] 2021-01-13 20:10
@Zabi09 Below I have attached a txt file showing the Full Error Code as shown in Search Console. Please could you open this file, and tell me what this code means, and how to resolve them so as to possibly rectify the AMP errors, because I am still seeing the errors despite switching to WP QUADS plugin.
`
[AMP Error In Search Console.txt](https://github.com/ahmedkaludi/accelerated-mobile-pages/files/5810847/AMP.Error.In.Search.Console.txt)
`

**Comment by Empathyfine** [comment] 2021-01-14 14:35
@Zabi09 please come to my assistance here. The error still persists, check the screenshot below

https://snipboard.io/Y9Fly4.jpg

**Comment by Zabi09** [comment] 2021-01-15 06:26
@Empathyfine I have tested some of your URLs and didn't find any errors - https://search.google.com/test/amp?id=8fLMcX8e8RC7D1_NvEVc6Q

Can you go to the AMP section of your website in the google search console and tell me how many pages have amp errors - https://prnt.sc/wnzg1o

**Comment by Empathyfine** [comment] 2021-01-15 14:11
@Zabi09 here is the screenshot of the pages with Error; https://snipboard.io/oDwOUx.jpg

And when I open the first Error, and tried to inspect [this first URL](https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/), this is what I see > https://snipboard.io/gS7v81.jpg

Meanwhile, I have placed all my Adsense codes very well in the AMP plugin and in the QUADS plugin.

Please kindly cross check thing for me. I will appreciate your assistance on this. Thanks and looking forward!

**Comment by Empathyfine** [comment] 2021-01-15 14:30
This URL here also shows a different kind of error; [click here for the URL](https://www.visaflux.com/tag/omg-game-play-on-facebook-messenger/amp/)

See the Error code it is showing here https://snipboard.io/Ft3kAn.jpg

I do not understand what is this codes in the error which beings with something like this "<Style amp-custom> @font-face{font-
family: 'poppins' ;font-
display :swap ;

Please your recommendations will be highly appreciated!

**Comment by Empathyfine** [comment] 2021-01-17 18:48
Hello @Zabi09 please I am still looking forward to you assistance on my issue.

**Comment by Zabi09** [comment] 2021-01-18 09:12
@Empathyfine I have checked your website again and found that the errors are back on your website - https://prnt.sc/x43hx3

Will you please tell us how you are adding the ads in WP QUADS plugin? and also have you deleted the previous ads which you were adding with the quick Adsense plugin? Please let us know so that I can check it and help you

**Comment by Empathyfine** [comment] 2021-01-18 17:39
@Zabi09  Here is the screenshot of my Ads set up in WP QUADS plugin; ==> https://snipboard.io/qiWRDK.jpg

Meanwhile, I have deleted the previous ads from Quick Adsense. And most importanly, there is no more such Ads with  ads slot (6403094387) as shown in the screenshot you shared above, so I do not know where google is capturing that from. I deleted them the day I installed WP QUADS plugin.

Such Ad is not in my AMP plugin, not in the Ad inserter plugin, Not in the WP QUADS plugin, not in my theme header, not in quick Adsense.

So I do not know where they are picking it up from.

Meanwhile, I have attached the screenshot of how I set up my ad in the WP QUADS plugin>> https://snipboard.io/qiWRDK.jpg

Please cross check and help me out

**Comment by Zabi09** [comment] 2021-01-19 11:42
@Empathyfine I have tested your pages again and now it is showing valid - https://prnt.sc/x7jtzu

Please click on the validate fix button in the search console and it is be fixed

**Comment by Empathyfine** [comment] 2021-01-19 14:08
@Zabi09 honestly, I do not understand the issue with Google search console, they are complaining that this page has AMP issue [see this link](https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/)

I do not know where they are picking that Ads and its associated error message from. Meanwhile the link you tested passed. How would one page pass and the other one will not pass. I did not do any specific setting for any specific page. So I don't know why one page will pass the AMP test and the other one will not pass. Meanwhile, that Ads code they are showing is NO MORE anywhere in my website.

Please could you test this [link](https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/) in your end.

Please what can you suggest I do about this issue?

**Comment by Zabi09** [comment] 2021-01-20 11:02
@Empathyfine Tested the link which you have sent me and its showing valid - https://search.google.com/test/amp?id=wkTG28kR5WvyR_EkKVlUCw

Will you please clear all the cache plugins before clicking on validate fix button and also can you send us a video of exactly where the errors are showing in the Google search console. So that I can check the same

**Comment by Empathyfine** [comment] 2021-01-22 08:30
@Zabi09 I just requested for validation again, and this time none has failed. Some pages have passed the validation test on GSC, so I wait for the validation to complete. But if anyone of them fails, then I will take a video of the error and share with you.

But for none of the pages to have failed since 2 days now, there is hope the whole pages will pass the validation test now. Just keeping the fingers crossed. Thanks for your time, attention and support. I appreciate.

I will come back to share the update at the end of the whole validation. Cheers!

**Comment by Empathyfine** [comment] 2021-01-24 02:44
Helllo @Zabi09 the problem persists; [Check this URL again.](https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/) . I don't know why some pages passed but this one failed, and once one fails, the whole validation process will pause.

i don't know why some will pass, and some will fail. Meanwhile none of ads settings or general settings was made for a single page.  So if there is AMP issue, it should affected all other pages, and not just only this one URL. And this one URL makes hard for google to continue validation for other ones.

Please what can I do?

**Comment by Empathyfine** [comment] 2021-01-24 03:23
@Zabi09 I have made this 10 minutes video of the AMP issue, just to show you every details you need to see. [Please watch video here](https://www.dropbox.com/s/ni0vai5iztwig4z/AMP%20Error%20Video.wmv?dl=0)

Please note, the video does not have sound, but I used text to make some points out.

Thanks and looking forward to your kind response.

**Comment by Zabi09** [comment] 2021-01-25 12:19
I have checked your website and all your posts are working fine without any errors and as you said one page is only having the error and I have checked that page and found that it is showing the old data only and its been cached by WP super cache, Will you please clear that and I hope that will also be fixed

**Comment by Empathyfine** [comment] 2021-01-27 14:28
@Zabi09 thank you for giving your time and attention. I have done as you recommended, and since I requested for validation, things have been looking good. Although it is still in progress, but if it were before, it would failed by now. So I am hopeful this recommendation will take care of it completely.

Still waiting for the validation to complete, and that will take days to few weeks, you know how google do! Once everything is completed, I will be glad to share. Thank you once more!

**Comment by Zabi09** [comment] 2021-02-02 07:05
@Empathyfine Any update on this?

**Comment by Empathyfine** [comment] 2021-02-02 07:45
@Zabi09  Honestly, the validation failed again. And this particular [URL](https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/) is the problem.

When I try to validate again, during the initial quick validation, the URL will cause it to fail. Google continue to see that particular URL as an affected page. I don't know what to do again.

**Comment by Zabi09** [comment] 2021-02-02 08:59
I have checked all your URLs and seems everything is showing valid except this one only - https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/ and when I check the same in AMP validation then its showing passed - https://prnt.sc/y04o8p

What I suggest you is to delete this post and create the same new post again because the problem is that a particular post is being cached and it is not getting clear and Google is seeing the old content only and not the new one.

**Comment by Empathyfine** [comment] 2021-02-02 09:39
Yes, though I did that before, but I re-created the post immediately.

But this time, I am going to delete it permanently and leave it for a longer time before recreating it, and that's if I will even bother recreating it.

But my concern is, since Google has cached this URL, won't they continue to see this error even after I delete the post. Until then, I am going to delete the URL, and then go back for validation two days after.

**Comment by Zabi09** [comment] 2021-02-02 12:23
Yes if you delete that particular post then also it will be cached by Google and it takes a maximum of 2-3 days for Google to deindex that post and once it is removed you can add a new post and I suggest you add it after 4-5 days.

Hope it helps

**Comment by Empathyfine** [comment] 2021-02-02 12:42
Okay, I will do just that!

I have deleted the post already, and I am just going to wait for 4-5 days as you suggested. Thanks for the support!

**Comment by Zabi09** [comment] 2021-02-02 12:45
It will definitely be fixed for sure and also all your website is validated, So, closing the ticket.

**Closed by Zabi09** 2021-02-02 12:45 UTC
