### ISSUE TITLE
There should not be a List UL 

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#3212] opened 2019-05-22 00:11 UTC
https://monosnap.com/file/Jv2Mkm9c3WcNYKuOlCA0HRAbDZSwRS

**Comment by RajuJeelaga** [comment] 2019-06-03 07:31
@ahmedkaludi  The problem is fixed in this ticket
Please see here  
https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3222

**Closed** 2019-06-03 11:20 UTC
Labels: [Priority: HIGH], bug
