### ISSUE TITLE
Turn on/off option for Excerpt to display in the Single - by default the option should be turned off  

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#806] opened 2017-04-29 06:53 UTC
Turn on/off option for Excerpt to display in the Single - by default the option should be turned off

**Comment by MohammedKaludi** [comment] 2017-05-06 15:44
Tested and it is Working.

**Comment by timmson87** [comment] 2017-05-13 03:21
No, the issue is absolutely not fixed. Even after the latest update stating that this issue has been fixed with Yoast. The OG meta descriptions do not show. And it's happening on many sites running Genesis that I've checked.

**Comment by ahmedkaludi** [comment] 2017-05-13 08:09
@timmson87 can you please share the URL of one of the website?

**Comment by MARQAS** [comment] 2017-05-13 09:16
Tested on my end and it's working 
@timmson87 Can you provide us more details on it?

**Comment by pegazee** [comment] 2017-05-13 09:22
I have just tested on my end and working perfectly fine

**Comment by timmson87** [comment] 2017-05-13 11:01
My apologies. I was actually referring to a separate issue with this plugin to do with meta tags. I've accidentally posted this in the wrong place.

**Comment by timmson87** [comment] 2017-05-13 11:02
This issue has in fact been solved.

**Comment by MohammedKaludi** [comment] 2017-05-15 07:05
@timmson87 does the issue still persists with meta tags? If yes, then can you please share the url and more details about it, I will personally make sure that issue gets fixed.

Thank you for reporting and getting back to us so swiftly.
Mohammed Kaludi

**Comment by timmson87** [comment] 2017-05-15 09:01
Hey Mohammed,

Yeah, this issue has been going on for some time now.

Basically, if I set my site to use a ‘static home page’ then the meta info displayed is totally wrong on every blog post. Rather than display the actual meta info as normal on each post, the post uses the homepage meta title and description instead, on every single blog post.

It might be Genesis specific but it's not a plugin conflict because it happens on a new site.

I went over this issue for hours trying to figure it out, but somehow I stumbled onto working out that if I set a static home page, the issues begin. But if the homepage is set to ‘latest blog posts’ then all is well. I'm not an expert with this stuff by any stretch, this was just my observation.

I've setup a test site: http://atmospherepro.siterubix.com/example-post-title/amp

You can see that when you view the page source for the AMP version, the meta info is wrong. When you view it for the standard version, it's perfect.

You will also see that when you change the homepage to 'latest blog posts' the issue goes away. At least, this was the case when I tested it a while ago.

Username: admin
Password: c1Gnts1M

I know this is a public forum but this is just a test site so I figured I'd post the login info here. It's running Genesis, Atmosphere Pro theme.

Thanks for your time on this! Cheers

**Comment by MohammedKaludi** [comment] 2017-05-21 11:45
@timmson87,

thank you for explaining the issue in detail and I have created a separate ticket for this issue https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/850 I will personally look into the issue and make sure it is fixed, also thank you for providing the login info as well, it really helps understand and test the issue.

I'm closing this ticket further communication will be done on #850 

Mohammed Kaludi

**Closed by MohammedKaludi** 2017-05-21 11:45 UTC
