### ISSUE TITLE
Mobile Redirection not working on 0.9.61and 62 version

### ISSUE THREAD

**Issue by pegazee** [ahmedkaludi/accelerated-mobile-pages#1151] opened 2017-09-26 09:13 UTC
It's working on the version 0.9.59, but when we update the plugin 0.9.61 or 0.9.62, mobile redirection functionality not working. One of our user reported this bug https://secure.helpscout.net/conversation/434897237/16331/?folderId=1060551

And I've not tested with 0.9.60 version, please test this version also.

**Comment by MARQAS** [comment] 2017-10-09 14:00
It's working fine at my end.
Can I get more detailed info on this? or the sites of the users who are actually having this issue?

**Comment by MARQAS** [comment] 2017-10-10 06:51
Might be this issue was due to session? If that's the case it has been resolved in the previous update.

**Comment by Cry0nicS** [comment] 2017-10-12 11:36
As seen on [this ](https://esportsmedia.ro/)website (if I'm not mistaken, you already inspected it with admin rights), the issue is still not resolved.

Downgrading to 0.9.61 still works, tho.

**Comment by ahmedkaludi** [comment] 2017-10-14 21:24
@MARQAS We need to work with the users on fixing their issues. I am putting this back in the next version. We need to spend as much time as we have to but figure this out

@Cry0nicS I am sorry for this, It's a bit complex. I assure you that this will be fixed in the next update for sure.

**Comment by ahmedkaludi** [comment] 2017-10-22 13:41
@Cry0nicS We are still not aware of the reason behind the issue as it works for other users... Any help from others would be appreciated.

**Comment by Cry0nicS** [comment] 2017-10-31 14:11
@ahmedkaludi I tried everything I could think of. From cloudflare to local changes. Nothing seems to work on versions post 0.9.59. Any prior version works just fine.
Can it be related to the change of the original AMP plugin, not being required in the newer versions anymore? Can't figure out where else to look.

**Comment by sharply46** [comment] 2017-11-03 09:00
@ahmedkaludi Hello , I am using the plugin and I noticed that the redirect only works if you have HOMEPAGE selected in general settings. I want to use amp feature just for my posts and the mobile redirect is not working unless i select the homepage also.
I assume you have a condition in the code related to Homepage selected.
Would be great if this condition is reworked so that we can use amp feature for only posts / pages / etc.

**Comment by Cry0nicS** [comment] 2017-11-03 09:11
@sharply46 That's it! That's what fixed the issue. Amazing catch!!! I tried many combinations, but couldn't have thought of this one!
@ahmedkaludi Can you investigate and let us know if there's a fix for this?

**Comment by zabi332** [comment] 2017-11-03 10:11
Two more issues of mobile redirection not working after updates

Ref: https://secure.helpscout.net/conversation/451748514/17214?folderId=1060551
Ref: https://secure.helpscout.net/conversation/459821189/17826?folderId=1060551

**Comment by ahmedkaludi** [comment] 2017-11-04 09:21
Another report: https://wordpress.org/support/topic/redirection-does-not-work-2/

**Comment by MohammedKaludi** [comment] 2017-11-04 14:59
Yes, the issue is valid and I have found the bug, and will push the code in today's update.

Code added https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/7aee9ccdd42cdf2583349bf2cb5702e84f165459

Needs testing a bit before the merge.

**Comment by ahmedkaludi** [comment] 2017-11-04 15:58
@Cry0nicS @sharply46  Can you please download this development version and see if that fixes the issue?
​
https://github.com/ahmedkaludi/accelerated-mobile-pages/archive/Development-0.9.67.zip
​

**Comment by sharply46** [comment] 2017-11-06 06:46
@ahmedkaludi Thank you for the feedback , but in my case the fixes are not working. 

I have added a temporary fix by removing the if condition at line 85 in redirect.php.

I added this fix so mobile redirect works when only posts are selected in general settings.
I haven't tested other options yet sorry.

**Comment by MohammedKaludi** [comment] 2017-11-06 06:55
@sharply46 the current fix in development is still not working?

Yes, there was a wrong condition in line no 122 https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/redirect.php#L122

But I have fixed and rewrote the redirection code. Can you please tell let me know, are you still facing the same issue?

Thank you for your feedback.

**Comment by sharply46** [comment] 2017-11-06 07:01
@ahmedkaludi  the fix in the development is not working indeed.

At line 85 you have a condition: 
if( $redux_builder_amp['ampforwp-homepage-on-off-support'] == 0 ){
       return;
 }

This returns if you don't have homepage selected. In my case I don't want the homepage , just posts.
Commenting this , worked for me . I'm not sure about other options tho. The algorithm is fairly complex and I don't think I have time and I'm not even sure how you want to implement it to even try to fix it.

**Comment by MohammedKaludi** [comment] 2017-11-06 07:10
@sharply46 Yes, you are right.

I somehow missed that one, thank you for your feedback. 
I just have to tweak it a bit so it can only stop the redirection when we are on the homepage.

Updating the code right now.

Mohammed Kaludi

**Comment by sharply46** [comment] 2017-11-06 07:16
@ahmedkaludi Sounds good , thank you very much  :)

**Comment by MohammedKaludi** [comment] 2017-11-06 10:11
@sharply46 and @Cry0nicS it should work now. Can you please check once if you can.

I'm also testing it in multiple environments.

Thank you.

**Comment by MohammedKaludi** [comment] 2017-11-06 14:00
Tested on multiple environments and it is working.

**Closed by MohammedKaludi** 2017-11-06 14:00 UTC
Labels: bug
