### ISSUE TITLE
Lightbox Issue: The main tag for the "amp-lightbox-gallery extension script" tag is "body"

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#5021] opened 2021-05-15 10:34 UTC
User having an issue with The main tag for the "amp-lightbox-gallery extension script" tag is "body"
Website: https://canovaonline.com/listing/immobile-rif-2272-due-monolocali-in-vendita-a-borgomanero-no/?amp
Reference: https://secure.helpscout.net/conversation/1506233655/195164?folderId=4195936

**Comment by andre-74** [comment] 2021-05-15 11:47
The problem is in AMP plugin.
Before the last update it worked fine, after the updating amp-lightbox-gallery effects don't show: the script code doesn't appear between head tags if you show the code of the page.
For a fast resolving our webmaster tried to copy and paste the script from head to the body section (in Wordpress, see amp menu/settings/advanced settings).

The problem is that currently the lightbox effects runs correctly but Google reports an issue for the tag body

See photos
Thanks

![WhatsApp Image 2021-05-15 at 13 16 11](https://user-images.githubusercontent.com/83794716/118359471-f0c94e80-b583-11eb-8442-4442c8d2d6e5.jpeg)
![WhatsApp Image 2021-05-15 at 13 10 54](https://user-images.githubusercontent.com/83794716/118359485-fcb51080-b583-11eb-8068-cf07d850b33a.jpeg)

**Comment by andre-74** [comment] 2021-05-18 22:12
After updating of pluging the issue still remains. Look at the amp test page I provided:
https://canovaonline.com/test-amp-page/?amp
If you search for the code you will not see the script amp-lightbox-gallery into the header section.
The Advanced Settings Menu seems to fail so I manually copy and paste the code into the HTML in Body and finally the carousel with lightbox worked but Google retried AMP error!

**Comment by Zabi09** [comment] 2021-05-19 05:21
@andre-74 We are going to fix your issue in the next update in version 1.0.77.1 after that you no need to add the amp-lightbox-gallery script manually and we adding it dynamically so please update our plugin to 1.0.77.1 which is going to get pushed today and remove the script which you are adding into the HTML in Body and your issue will be fixed

**Comment by andre-74** [comment] 2021-05-19 07:52
Thank You, great support!

**Comment by MohammedKaludi** [comment] 2021-05-19 09:30
@andre-74 we just pushed the update, can you please let us know that the issue is resolved at your end after the latest update so that we can close the ticket.

**Comment by Zabi09** [comment] 2021-05-19 09:37
Pushed in 1.0.77.1

**Closed by Zabi09** 2021-05-19 09:37 UTC
Labels: Urgent, [Priority: HIGH], bug
