### ISSUE TITLE
Sub menus not seen in AMP due to  aku-child theme

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#3164] opened 2019-05-09 11:15 UTC
Issue recreated on local
The theme is available in Magazine3 telegram group with its parent theme aku
HelpScout Link: https://secure.helpscout.net/conversation/846113298/65211?folderId=2770545

**Comment by Zabi09** [comment] 2019-05-22 05:56
Unable to recreate on localhost and also the issue is not recreating on the user end also. So closing this ticket.

**Closed by Zabi09** 2019-05-22 05:56 UTC
Labels: [Priority: HIGH]
