### ISSUE TITLE
Mobile redirection not working properly.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/accelerated-mobile-pages#3370] opened 2019-06-27 13:33 UTC
Mobile redirection not working properly.
Steps to be followed:
1. Deactivate AMP for WP plugin.
2. Create a new page.
3. Activate AMP for WP plugin and turn on mobile redirection.
4. The page will not be redirected to AMP on mobile.
Ref: https://secure.helpscout.net/conversation/880003491/70798?folderId=2322649

**Comment by pegazee** [comment] 2019-06-28 07:44
The issue is occurring on the master. And I've committed the code in the master branch.

**Comment by MohammedKaludi** [comment] 2019-06-28 11:54
Ready to deploy.

**Comment by MohammedKaludi** [comment] 2019-07-02 17:24
Pushed in 0.9.97.61

**Closed by MohammedKaludi** 2019-07-02 17:24 UTC
Labels: NEED FAST REVIEW, [Priority: HIGH], bug
