### ISSUE TITLE
Unable to add STN video Ads due to the outdated tag.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/accelerated-mobile-pages#5334] opened 2022-11-14 06:30 UTC
The users are unable to implement videos by STN videos due to the outdated tag.

Ref ticket: https://magazine3.in/conversation/65632?folder_id=4

**Comment by akshaywali** [comment] 2022-11-21 14:09
pushed in 1.0.77.54

**Comment by sajandara** [comment] 2022-12-02 08:53
AMP iframe improvement.
Reference ticket: https://magazine3.in/conversation/75450?folder_id=27

**Comment by garretthyder** [comment] 2023-01-02 17:29
Thank you @akshaywali for the support.

Testing the latest release, one minor regex logic issue cropped up for me.

If you have the 'Video Docking' toggle disabled it goes through the following code in the logic;
```
if(preg_match('/<amp-video-iframe(.*?) dock|dock=">/', $content)){
	$content = preg_replace('/<amp-video-iframe(.*?) dock|dock=">/','<amp-video-iframe $1>', $content);
}
```

This outputs an extra '>' symbol, see screenshot;
![Screenshot 2023-01-02 at 9 22 41 AM](https://user-images.githubusercontent.com/8726005/210263042-64a557dd-31c0-4615-9a3f-d87a2eec569a.png)

When Video Docking is enabled there's no issue.

As this code block is a duplicate of others that support Video Docking I would assume they all have the same logical regex error.

In my local testing just removing the '>' closing of the tag in both the source and result of the preg_replace call resolves the issue for me.

All the best

**Comment by akshaywali** [comment] 2023-01-03 07:03
Thank you @garretthyder  for highlighting the issue. We will fix this in upcoming update

**Closed** 2023-01-11 06:56 UTC
Labels: enhancement, 3rd party Compatibility, Ready for Review

**Comment by garretthyder** [comment] 2023-01-11 08:52
Just a note, the same regex bug is still found on the following other sections in the same file for handling of dock;
- amp-video
- amp-youtube
- amp-brid-player
- amp-brightcove

Figured you'd want to apply the same fix just done for amp-video-iframe to these other contexts.
Cheers
