### ISSUE TITLE
Product review disappeared in AMP 

### ISSUE THREAD

**Issue by HaripriyaHari** [ahmedkaludi/accelerated-mobile-pages#4636] opened 2020-07-15 14:50 UTC
When a user using Product Review Lite plugin, the AMP page is not showing.
Reference: https://wordpress.org/support/topic/product-review-disappeared-in-amp/

**Comment by Zabi09** [comment] 2020-07-17 11:01
Going to fix in - https://wordpress.org/support/topic/product-review-disappeared-in-amp-2/

**Comment by MohammedKaludi** [comment] 2020-07-23 09:55
The issue is due to WP Product Review Lite  and  not with ampforwp

they are looking into the issue 
https://wordpress.org/support/topic/product-review-disappeared-in-amp-2/

Closing the issue.

**Closed by MohammedKaludi** 2020-07-23 09:55 UTC
Labels: [Priority: HIGH], bug
