### ISSUE TITLE
Converting Internal links into AMP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1156] opened 2017-09-26 13:22 UTC
these internal links will be altered to /linking_to another_page/amp
It would be great if external links are left untouched.

REF: https://wordpress.org/support/topic/link-url-within-pages/#post-9525594

**Comment by Frenchomatic** [comment] 2017-09-28 16:07
I can see this being very troublesome for your support : as mentioned, this would need to be some type of option. There are many case where you may not wish to link to an amp version. The logic would also need to be if amp endpoint exists. Part of the issue is a lack of understanding by some that amp is not a one-to-one replacement for a mobile version.  Google treats amp pages individually based upon their merits and validated code.

**Comment by githubjabbar** [comment] 2018-03-21 08:04
Wondering if it's possible to change all links which are inside post's contents to link to the AMP version of the linked posts?

REF: https://secure.helpscout.net/conversation/545247339/23491?folderId=1060556

**Comment by ToufiqSuhail** [comment] 2018-05-24 12:29
Another one: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/1538

**Comment by MohammedKaludi** [comment] 2018-06-11 09:28
Fixed in #2204 
Closing the ticket.

**Closed by MohammedKaludi** 2018-06-11 09:28 UTC
