### ISSUE TITLE
CSS of the layout breaks due to server cache(Tree Shaking)

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/accelerated-mobile-pages#4397] opened 2020-04-24 10:55 UTC
Ref: https://secure.helpscout.net/conversation/1140086190/123622/

Screenshot:
1.  https://prnt.sc/s55lut
2. https://prnt.sc/s55m7y

The issue seems to be coming from the MU Cache plugin. 
Screenshot: https://prnt.sc/s563y1

We need to test it. The issue didn't reoccur every time. It happens almost after two-three days.

**Comment by MohammedKaludi** [comment] 2020-05-23 10:24
the issue is due to a conflict with amp cache and proxy cache purge plugin.

Issue fixed on users end and created a ticket in Extension area.

https://trello.com/c/l4BBxYn1/1770-amp-cache-conflicts-with-proxy-cache-purge

**Closed by MohammedKaludi** 2020-05-23 10:24 UTC
Labels: Urgent, [Priority: HIGH], bug
