### ISSUE TITLE
Six AMP Error Issues in Google Search Console

### ISSUE THREAD

**Issue by Empathyfine** [ahmedkaludi/accelerated-mobile-pages#4947] opened 2021-03-04 13:38 UTC
Hello @Zabi09 , previously I mentioned the following errors in a former case I presented which you later closed hoping that everything will be fine after few days as I deleted some of the affected pages. Here is to let you know that I still have these issues in the GSC.

Below are two examples of the affected pages, which I have deleted the post a very long time ago (even before you closed my previous case long ago). Now these issues are still there. And I have purged all my caching plugins and clear all caches.

Please why am I still having these AMP Error issues, and what do I do please?

**1.** Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head.

**2.** Custom JavaScript is not allowed.

**3.** Tag or text which is only allowed inside the body section found outside of the body section.

**4.** URL not found (404)

**5.** Referenced AMP URL is not an AMP

**6.** Crawl issue

Examples of the 2 affected pages;

[Here](https://www.visaflux.com/facebook-hook-up-text-messages-facebook-hook-up-near-me/amp/)

And [here](https://www.visaflux.com/opera-mini-internet-browser-app-free-download-opera-mini-browser-download-app/amp/)

**7.** Invalid URL protocol in attribute 'src' of tag 'amp-img'.

The 7th issue is in another website, please how do I resolve the "Invalid URL protocol in attribute 'src' of tag 'amp-img'." issue too. And here is the link to the page for the 7th issue [here](https://www.fanslite.com/create-wordpress-com-account-create-wordpress-com-account/amp/)
Please help me suggestions.

**Comment by Zabi09** [comment] 2021-03-05 09:55
@Empathyfine When I tested your website in AMP test - https://search.google.com/test/amp - then I can see the ads code in a header which is not allowed in AMP - https://prnt.sc/10dki4i and when I test your website in - https://validator.ampproject.org/ - then I don't see any errors here, So the problem is with the cache and if you already cleared the cached then will you please clear the serverside caching if any and let you know,

and about your 7th issue - Will you please add the image properly see this on the non-amp - https://prnt.sc/10dk6dj and due to this improper image you are having errors in AMP, Will you please replace it with a proper image and it will fix your issue.

**Comment by Empathyfine** [comment] 2021-03-05 18:32
Okay @Zabi09 , I will do, and share update here accordingly! Thanks for your response!

**Comment by Zabi09** [comment] 2021-03-16 13:00
@Empathyfine Have you cleared the cache?

**Comment by Empathyfine** [comment] 2021-03-16 18:34
@Zabi09 , yes I did, but still having the same issue. But just right now, I decided to delete all my Sitemaps, and I will wait for 2days to re-submit all sitemap. I want to see if that will help. What do you think about this?

**Comment by Zabi09** [comment] 2021-03-17 10:26
@Empathyfine For AMP pages you no need to send for sitemap as Google will automatically crawl it, ok anyways do that and let us know what happened after that.

**Comment by Zabi09** [comment] 2021-03-22 07:09
@Empathyfine I have checked your website and found that it's valid now.

https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=O4x1_YfaHaq5wXsWdrZ4EA
https://search.google.com/test/amp?utm_source=gws&utm_medium=onebox&utm_campaign=suit&id=JdUs8Q13KRVBgh3tnVk7Og

So closing the ticket

**Closed by Zabi09** 2021-03-22 07:09 UTC
Labels: Need More Data
