### ISSUE TITLE
Rare issue with custom permalink

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#2981] opened 2019-03-27 11:10 UTC
Ref: https://secure.helpscout.net/conversation/806692035/60471?folderId=2632030

We have wp-admin login details and waiting for the FTP access.

These are the URL's in which we are facing the issue.

https://www.webveteran.com/blog/visual-code-editor/  **this URL works**
 
https://www.webveteran.com/blog/visual-code-editor/amp/      **It doesn't work  and gets 404 error**

**Comment by pegazee** [comment] 2019-03-30 11:41
The issue is occurring due to the configurations set up on the user end. And also contacted to user.

We can close this ticket.

**Closed by pegazee** 2019-03-30 11:41 UTC
Labels: Need Testing, bug
