### ISSUE TITLE
Compatibility with 'Site kit by Google'

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/accelerated-mobile-pages#3398] opened 2019-07-03 12:08 UTC
https://secure.helpscout.net/conversation/892537661/72351?folderId=2632028

The content is not rendering into AMP from the Gutenberg editor

**Comment by MARQAS** [comment] 2019-07-04 12:41
The issue is due to `Site Kit by Google` (https://sitekit.withgoogle.com/) which is currently in beta.
I have disabled it in AMP on users website using AMP plugins manager.

**Comment by ahmedkaludi** [comment] 2019-07-09 09:54
It was caused on the user's end. IT's solved.

He did not connected the sitekit, but we installed and we didn't connected as well but it was supposed to throw fatal and it didn't.

User has deactivated it and WE don't have the proper data or the user. So we will close it

**Closed by ahmedkaludi** 2019-07-09 09:54 UTC
Labels: 3rd party Compatibility, Need More Data, [Priority: MEDIUM]
