### ISSUE TITLE
Disqus Comments wont load in Swift design

### ISSUE THREAD

**Issue by SageFargo** [ahmedkaludi/accelerated-mobile-pages#3049] opened 2019-04-18 21:34 UTC
As title says, the Disqus comments add on won’t load, stuck on the loading animation. 
See image below: 
![940633E2-2D77-43DA-BEC5-8DED399A24D5](https://user-images.githubusercontent.com/40724154/56392705-ce489800-623a-11e9-810c-ee2af2587792.jpeg)

**Comment by SageFargo** [comment] 2019-04-22 10:58
@Zabi09 @ahmedkaludi can you look into this

**Comment by RajuJeelaga** [comment] 2019-04-22 12:49
@SageFargo Can you post the login info into the team@magazine3.com

**Comment by pegazee** [comment] 2019-04-27 12:09
@SageFargo , I'm working on this ticket. Can you please

**Comment by pegazee** [comment] 2019-04-30 06:13
@SageFargo,

I think the issue was occurring on your end. Please contact our support team, they will debug and help you to resolve the issue. And I'm closing this ticket, if the issue is valid we'll re-open this ticket.

**Closed by pegazee** 2019-04-30 06:13 UTC
Labels: Need More Data, Need Testing
